### ISSUE TITLE
Code Compilation Error with latest commit 

### ISSUE THREAD

**Issue by sidhishruti22** [open-component-model/ocm-controller#135]
`Make build` getting failed.

Version & Tag: v0.3.0 & e1e41b5 

Error : ` controllers/snapshot_controller.go:90:20: too many errors `

More Info: Screenshot attached

<img width="1008" alt="Screenshot 2023-02-27 at 10 23 20 AM" src="https://user-images.githubusercontent.com/124029673/221477356-f12692cd-adb4-4614-a926-35737dbf927c.png">

**Comment by phoban01** [comment]
HI @sidhishruti22, looks like you need to update to Go 1.20 😄 https://tip.golang.org/doc/go1.20#errors

**Comment by mayankraipure12** [comment]
There should be a minimum requirement given on the site of go lang combability version.
