### ISSUE TITLE
Error while executing Parent child approach in componentversion.yaml (of parent component)

### ISSUE THREAD

**Issue by sidhishruti22** [open-component-model/ocm-controller#144]
here it is failing https://github.com/open-component-model/ocm-controller/blob/main/controllers/componentversion_controller.go#L160 .
Example executed:  https://github.com/Skarlso/podify-public

Error snippet attached
<img width="1779" alt="Screenshot 2023-02-28 at 2 28 32 PM" src="https://user-images.githubusercontent.com/124029673/222330508-4cb3e65c-96c6-4653-b152-39191f4bd59b.png">

**Comment by sidhishruti22** [comment]
`2023-03-02T07:26:51Z	ERROR	Reconciler error	{"controller": "componentversion", "controllerGroup": "delivery.ocm.software", "controllerKind": "ComponentVersion", "ComponentVersion": {"name":"ocm-app-podify","namespace":"ocm-system"}, "namespace": "ocm-system", "name": "ocm-app-podify", "reconcileID": "d25c8562-ae3d-4f34-b560-a9fafd80b377", "error": "failed to check version: failed to get latest component version: failed to get component versions: failed to list versions for component: ghcr.io/sidhishruti22/ocm-app-ex-podify/component-descriptors/ghcr.io/sidhishruti22/ocm-app-podify: not found"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235`

**Comment by sidhishruti22** [comment]
working on this model:  https://github.com/sidhishruti22/ocm-app-podify

**Comment by sidhishruti22** [comment]
facing Issue while reconciling the root component which has the reference of other child components .

**Comment by Skarlso** [comment]
Hm, it looks like the component with that specific name does not exist.

**Comment by sidhishruti22** [comment]
the issue still persist using this example as reference:  https://github.com/Skarlso/podify-public. (the issue pasted in the description ).
Also some other ways to implement, using this : https://github.com/open-component-model/ocm-spec/blob/main/doc/scenarios/README.md.
however, closing this issue and create a new one , if any error occurs while executing the step by using the above link mentioned ^^.
