### ISSUE TITLE
Introduce linter config

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm-controller#145]
Tsk, tsk, tsk. We are missing a good linter config.

**Comment by robertwol** [comment]
@Skarlso  https://cuelang.org/docs/integrations/go/ ❓

**Comment by Skarlso** [comment]
I'm not following your question Robert I'm afraid.

**Comment by Skarlso** [comment]
Applying it to the other controllers as well.

**Comment by Skarlso** [comment]
Linter for product controller will be added after https://github.com/open-component-model/mpas-product-controller/pull/66 is merged.
