### ISSUE TITLE
make build for controller doesn't work as well on windows

### ISSUE THREAD

**Issue by mayankraipure12** [open-component-model/ocm-controller#152]
$ git clone https://github.com/open-component-model/ocm-controller.git
$ make deploy
mkdir -p /c/project/ocm/workspace/ocm-controller/bin
GOBIN=/c/project/ocm/workspace/ocm-controller/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.0
/c/project/ocm/workspace/ocm-controller/bin/controller-gen rbac:roleName=ocm-controller-manager-role crd webhook paths="./api/..." paths="./controllers/..." output:crd:artifacts:config=config/crd/bases
-: no Go files in C:\project\ocm\workspace\ocm-controller\api
Error: not all generators ran successfully
run `controller-gen rbac:roleName=ocm-controller-manager-role crd webhook paths=./api/... paths=./controllers/... output:crd:artifacts:config=config/crd/bases -w` to see all available markers, or `controller-gen rbac:roleName=ocm-controller-manager-role crd webhook paths=./api/... paths=./controllers/... output:crd:artifacts:config=config/crd/bases -h` for usage
make: *** [manifests] Error 1
Kindly look into this issue urgently

Workaround on windows currently: Installing controller via wsl2 ubuntu

**Comment by mayankraipure12** [comment]
Hi @Skarlso , So can we close the ticket or wait for the update for the feature to be included in furture releases.

**Comment by Skarlso** [comment]
We can close it. I don't believe we are going to work on this anytime soon.
