### ISSUE TITLE
possibility to  disable/stop executing a crd via config

### ISSUE THREAD

**Issue by mayankraipure12** [open-component-model/ocm-controller#157]
Problem:
If files are present eg : componentversion.yaml, resources.yaml, localization.yaml, kusomization.yaml . It automatically picks and execute the controller chain for reconcilation . 
In case of error in localization or resource , If I only want to execute the controller chain till resource not afterwards even the localization file exists.
Current Solution:
    Need to remove the files from the source code and bring it in one by one to execute this.
I am not sure if there are other ways to do this

Proposed way:
   Implementation of enabling/disabling a controller from reconciling the file for that project from the yaml file

eg: 
apiVersion: delivery.ocm.software/v1alpha1
kind: Localization
metadata:
  name: vault
  namespace: ocm-system
spec:
  interval: 1m0s
  **enable: true/false** +optional (default true)
  componentVersionRef:
    name: vault
    namespace: ocm-system

if enable: false , then localization controller won't pick the file for reconcilation and later controllers also won't take the files
This will help us keep the config files eg: localization.yaml , kustomization.yaml in the source code and give user the ability to control to verify if any issue persists.

This change require to introduce a property in schema and corresponding controller to handle such a case.

**Comment by Skarlso** [comment]
We can add a `suspend` value.
