### ISSUE TITLE
make dev-deploy doesn't work in ubuntu wsl2

### ISSUE THREAD

**Issue by mayankraipure12** [open-component-model/ocm-controller#165]
Trying to deploy ocm-controller via make dev-deploy throws an error

mayank@W-8TTJ633:~/controller/ocm-controller$ make dev-deploy
mkdir -p config/dev && cp -R config/default/* config/dev
cd config/dev && kustomize edit set image open-component-model/ocm-controller=ghcr.io/open-component-model/ocm-controller:latest \
&& kustomize edit add patch --path ./patches/init-container.yaml \
&& kustomize edit set image open-component-model/ocm-registry=ghcr.io/open-component-model/ocm-registry:latest
bash: kustomize: command not found
make: *** [Makefile:133: dev-deploy] Error 127

**Comment by Skarlso** [comment]
`make dev-deploy` doesn't run `kustomize` target beforehand. Run `make kustomize && make dev-deploy`.

**Comment by phoban01** [comment]
@mayankraipure12 Why not use the official deployment method?

```ocm controller install```

**Comment by Skarlso** [comment]
I know why. `dev-deploy` doesn't run `kustomize`.

**Comment by mayankraipure12** [comment]
![image](https://github.com/open-component-model/ocm-controller/assets/120610939/0c707e8a-1ccd-45ac-994a-94fbf12c2eab)

Still this issue persists, shall we stop using make dev-deploy

**Comment by Skarlso** [comment]
I left one out. 🤦
