### ISSUE TITLE
Support for multiple ComponentVersions and Rollback 

### ISSUE THREAD

**Issue by robertwol** [open-component-model/ocm-controller#170]
this is related to the following issue: https://github.com/open-component-model/ocm-controller/issues/159

ocm-controller should support rollback to previously known working version.
assuming following scenario flow:
1. we specify initial `ComponentVersion` e.g.
```YAML
version:
    semver: v1.0.0
```
This will trigger OCM-controller to pull specified version `v1.0.0` from OCI registry and create local copy for further deployment 
 
2. we bump the `ComponentVersion` e.g.
```YAML
version:
    semver: v1.0.1
```
This will trigger OCM-controller to pull the new version `v1.0.1` from OCI registry and create local copy for further deployment 

if the option `prune:` from https://github.com/open-component-model/ocm-controller/issues/159 is not active, we should have two versions of `componentdescriptor` CR in cluster
```bash
componentdescriptor.delivery.ocm.software/github.com-acme-podinfo-v1.0.0-10999154105985767822
   20d
componentdescriptor.delivery.ocm.software/github.com-acme-podinfo-v1.0.1-11333791066380101757
```

This is desired in some circumstances. therefore we should also define a parameter defining how may version we should keep; perhaps `keepNumberOfComponentVersion: 2`

3. NOW let say we identified there is a problem with new version and we want to downgrade the `ComponentVersion` to previously known working version e.g.
```YAML
version:
    semver: v1.0.0
```
This should  trigger OCM-controller to:
- check if the vision does not exists locally,  
- or pull old  version `v1.0.0` from OCI registry  

then version specified in  `ComponentVersion` should be use by deployer/operator to deploy application.

**Comment by Skarlso** [comment]
The reverting to a previous version should work with https://github.com/open-component-model/ocm-controller/pull/163.

Are you saying that it did not work?

Prune is mostly passed over to Flux. ComponentDescriptors are only used to gather version and resource information. Keeping them doesn't add too much value into the flow as they are dynamically recreated anyways once a version is reconciled. What benefit would be keeping the descriptors if the component version is removed/updated/reverted? Nothing accesses that information anymore.

**Comment by Skarlso** [comment]
Okay, so after a long discussion and some time in this area, we decided this is not a good idea. After installing a version, trying to return to a previous version is error-prone. Many unknown factors are involved with a version install, such as migrations, third-party component changes, state changes, persistent volume changes, secrets, component access, validations, etc... 

Rolling these back is near impossible without messing something up badly. The mindset we will adopt is an always-go-forward mindset. If a version is compromised, either delete it and install a previous version or bump it to a fix. Anything else leaves the cluster in an unknown state which is not desirable.

We will turn off the current functionality of the ability to specify a lower version than is currently installed. It won't error, but it will ignore that version.

**Comment by phoban01** [comment]
Roll-backs are also an attack vector that needs to be considered, especially in the context of a project such as OCM which is concerned with automated delivery.

**Comment by souleb** [comment]
> This is desired in some circumstances. therefore we should also define a parameter defining how may version we should keep; perhaps keepNumberOfComponentVersion: 2

We could keep several versions in cache like suggested. The use could then revert manually by changing the `semver`.

**Comment by Skarlso** [comment]
>We could keep several versions in cache like suggested.

We don't cache resources that point to these, like Kube objects. And we don't cache anything applied to the cluster that potentially modified like service accounts, secrets, etc. We don't keep a catalogue either, that's flux, I guess. In-fact without a resource like a snapshot no-one know where anything is. :D So once the objects are deleted, the storage is useless. ( We should even probably clean it up periodically ).

Further, and more importantly... our cache is a throwaway. It's not persistent storage in any way. Meaning it could be restarted, deleted, updated, whatever. It has two purposes. Provide ease on external repositories. Like having to fetch something constantly from the outside especially if it's big. And an integration point with Flux. Storing a version there is no guarantee that the actual thing is there.
