### ISSUE TITLE
Conceptual: Override "replicaSet" using kustomization 

### ISSUE THREAD

**Issue by sidhishruti22** [open-component-model/ocm-controller#178]
Hey team,
Is it possible to override the ReplicaSet (which is in deployment.yaml ) by using configData.?

**Comment by Skarlso** [comment]
I'm not sure I understand this question. What is it that you would like to achieve?

**Comment by sidhishruti22** [comment]
yeah to be more specific , is there any possibility for overriding replica set using ConfigData CRD.
for example : 
``` deployment .yaml```:
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: image1
  namespace: default
  labels:
    app: image1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image1
  template:
    metadata:
      labels:
        app: image1
    spec:
      containers:
      - image: noimage:v0.0.0
        name: image1
        ports:
        - containerPort: 9898
          name: http`
Here the value of "replicaset" in deployment.yaml file is 1. 
if it can be overridden by using configdata resource kind  : 
`apiVersion: config.ocm.software/v1alpha1
kind: ConfigData
metadata:
  name: ocm-config
localization:
  - name: image
    file: deployment.yaml
    image: spec.template.spec.containers[0].image
    resource:
      name: image
  - name: replicaSet
    file: deployment.yaml
    image: spec.replicas
    resource:
      name: replicaSet
      value: 3`
so here I am trying to override the "replicaset" from value 1 to value 3
would it be achievable ? 
I understand it can be achieved by changing the value in "deployment.yaml" file . please advise

**Comment by Skarlso** [comment]
Basically take the deployment, and create the same deployment, but replace the parts that you want and remove everything else, then run the merge.

**Comment by Skarlso** [comment]
Oh, I misunderstood `replicaSet` to change the deployment to a replicaSet... :D :D There is a much simpler way with ConfigData.

You can see an example here: https://github.com/open-component-model/MPAS/blob/main/examples/products/podinfo/app/backend/config.yaml

**Comment by sidhishruti22** [comment]
It worked using the example : https://github.com/open-component-model/MPAS/blob/main/examples/products/podinfo/app/backend/config.yaml .
