### ISSUE TITLE
ocm-controller doesn't get deployed to in second cluster

### ISSUE THREAD

**Issue by mayankraipure11** [open-component-model/ocm-controller#179]
I have create 4 cluster demo01, demo02, demo03 and demo04
I was successfully able to deploy controller on demo01 cluster but when I switch to cluster demo02
via kind export kubeconfig -n demo02. 
and run make deploy to ocm-controller , it fails with the error in image

![image](https://user-images.githubusercontent.com/56959636/234181018-5bd8f42e-3018-482b-871e-d75087ed89e4.png)

Could you kindly look this on priority since we have to do a demo

**Comment by mayankraipure12** [comment]
Issue with kind cluster on wsl2 ubuntu

**Comment by Skarlso** [comment]
You have a connection refused there. Something was wrong with your kube config. Not particularly the deployment's fault. Please make sure you can access the cluster with something like `kubectl get pods -A` before deploying.
