### ISSUE TITLE
OCM Controller deployment error

### ISSUE THREAD

**Issue by mohammad-ammar14** [open-component-model/ocm-controller#208]
Hello, I am trying to deploy ocm-controller to the kind cluster. I am getting error below 
" ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "GitRepository.source.toolkit.fluxcd.io", "error": "no matches for kind \"GitRepository\" in version \"source.toolkit.fluxcd.io/v1beta2\""} "

attached screenshots:

<img width="1510" alt="Screenshot 2023-06-06 at 10 49 50 AM" src="https://github.com/open-component-model/ocm-controller/assets/120632768/70abca41-9392-48f7-9de3-a43a880659d1">
<img width="1173" alt="Screenshot 2023-06-06 at 10 51 53 AM" src="https://github.com/open-component-model/ocm-controller/assets/120632768/371c7c20-ad1a-4b08-8ae6-ffdfd18da45b">

**Comment by Skarlso** [comment]
Right, so `flux install` is required for a cluster and ocm-controller now.

**Comment by robertwol** [comment]
@mohammad-ammar14 is that still a case, could you validate and update/close the issue if not longer relevant
