### ISSUE TITLE
`ocm controller install` does not create successful deployments

### ISSUE THREAD

**Issue by robertwol** [open-component-model/ocm-controller#285]
`ocm controller install` does not create successful deployment:
```shell
kc get po -n ocm-system
NAME                              READY   STATUS              RESTARTS   AGE
ocm-controller-6cff4d8758-ktgjx   0/1     ContainerCreating   0          12m
registry-6b7464647d-bbqxr         0/1     ContainerCreating   0          12m
```

events
```shell
Events:
  Type     Reason       Age                 From               Message
  ----     ------       ----                ----               -------
  Normal   Scheduled    13m                 default-scheduler  Successfully assigned ocm-system/ocm-controller-6cff4d8758-ktgjx to ocm-controller-control-plane
  Warning  FailedMount  70s (x14 over 13m)  kubelet            MountVolume.SetUp failed for volume "certificates" : secret "ocm-registry-tls-certs" not found
  Warning  FailedMount  5s (x6 over 11m)    kubelet            Unable to attach or mount volumes: unmounted volumes=[certificates], unattached volumes=[certificates kube-api-access-5tj66]: timed out waiting for the condition
  ```
  
  seems it's not even using latest image: `  Image:         ghcr.io/open-component-model/ocm-controller:v0.11.0`
  
  also deploying with `ocm controller install --version v0.13.0` does not seems to install different version of the image.
  
  using OMC cli:
  ```
❯ ocm --version
ocm version 0.4.1
  ```

**Comment by Skarlso** [comment]
```
secret "ocm-registry-tls-certs" not found
```

This is a required secret now. However that secret gets there, the cluster needs to be prepared to be able to run the ocm-controller. MPAS bootstrapper takes care of that but obviously installs more than just the ocm-controller.

There are certain prerequisite to the cluster in which the controller can run now.

**Comment by robertwol** [comment]
maybe the command should check the prerequisites before apply the deployment and show some error?

**Comment by Skarlso** [comment]
Precisely.
