### ISSUE TITLE
How to configure `Resource` CR `spec.sourceRef.resourceRef.version` for automated updates

### ISSUE THREAD

**Issue by jonasbreuer** [open-component-model/ocm-controller#404]
I am following the `Deploying the OCM Software Artifact` guide on the [website](https://ocm.software/docs/tutorials/build-deploy-infrastructure-via-helm-charts-with-ocm/#deploying-the-ocm-software-artifact).

The base resources from the guide work as expected and the Flux integration in successful.
I am now trying to adjust the CR's to automatically get the latest `ComponentVersion` including the latest resources of the component descriptor.

Using the `spec.version.semver` property of the ComponentVersion CR works fine:
```
apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: ocm-test
  namespace: ocm-system
spec:
  component: "github.tools.sap/deploy-with-confidence/ocm-test"
  interval: 10s
  references:
    expand: true
  repository:
    url: "eu.gcr.io/sap-dwc/ocm-test"
    secretRef:
      name: gcp-registry-pull-secret
  version:
    semver: ">=1.0.1"
```

When adjusting the `Resource` CR, I have learned that semver is not supported for `spec.sourceRef.resourceRef.version` property. Therefore, I am asking for guidance how the `version` of the resource should be configured to automatically get the latest resource version included in the component descriptor?

My assumption was to not set the `version` which results with the `tag: latest` in the created `Snapshot` CR.

Resource.yaml
```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: ocm-test-local-helm-echo-server
  namespace: ocm-system
spec:
  interval: 10s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: ComponentVersion
    name: ocm-test # latest component version will be used
    namespace: ocm-system
    resourceRef:
      name: helm-echo-server
      extraIdentity:
        helmChart: ocm-test-echo-server
```

Snapshot CR:
```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: Snapshot
metadata:
  creationTimestamp: '2024-04-22T12:25:11Z'
  finalizers:
    - finalizers.snapshot.ocm.software
  generation: 1
  name: ocm-test-local-helm-echo-server-3azfvfh
  namespace: ocm-system
  ownerReferences:
    - apiVersion: delivery.ocm.software/v1alpha1
      kind: Resource
      name: ocm-test-local-helm-echo-server
      uid: 725beff2-0c5a-4e3a-815f-e12a7396f070
  resourceVersion: '158207917'
  uid: d20d1733-a61a-4e05-b3db-361625ebaeb0
  selfLink: >-
    /apis/delivery.ocm.software/v1alpha1/namespaces/ocm-system/snapshots/ocm-test-local-helm-echo-server-3azfvfh
status:
  conditions:
    - lastTransitionTime: '2024-04-22T12:25:11Z'
      message: Snapshot with name 'ocm-test-local-helm-echo-server-3azfvfh' is ready
      observedGeneration: 1
      reason: Succeeded
      status: 'True'
      type: Ready
  digest: sha256:17146a867623205eeae868df5e2e9eb611c151520567728bbbb5c62e4f1dea36
  observedGeneration: 1
  repositoryURL: >-
    https://registry.ocm-system.svc.cluster.local:5000/sha-4286669090502006150/ocm-test-echo-server
  tag: latest
spec:
  digest: sha256:17146a867623205eeae868df5e2e9eb611c151520567728bbbb5c62e4f1dea36
  identity:
    component-name: >-
      github.tools.sap-deploy-with-confidence-ocm-test-1.0.4-12930407461330342590
    component-version: 1.0.4
    helmChart: ocm-test-echo-server
    resource-name: helm-echo-server
    resource-version: latest
  tag: latest
``` 
Is my understanding correct that the Snapshot version is completely decoupled from the real resource version in the component descriptor? In the component descriptor the version is `1.0.4` but this is not reflected in the `Resource` entity.

But it seems that the Flux controller has issues when pulling the Helm chart from the local OCI registry when the `latest` tag is being used in the Resource.
HelmChart CR Error: `chart pull error: failed to get chart version for remote reference: could not get tags for "ocm-test-echo-server": unable to locate any tags in provided repository: oci://registry.ocm-system.svc.cluster.local:5000/sha-4286669090502006150/ocm-test-echo-server`

Helm Chart CR:
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  creationTimestamp: '2024-04-22T12:25:12Z'
  finalizers:
    - finalizers.fluxcd.io
  generation: 1
  labels:
    helm.toolkit.fluxcd.io/name: ocm-test-local-helm-echo-server
    helm.toolkit.fluxcd.io/namespace: ocm-system
  name: ocm-system-ocm-test-local-helm-echo-server
  namespace: ocm-system
  resourceVersion: '158209186'
  uid: 29f41b23-a0b5-45b9-8eaf-02e11d237d1a
  selfLink: >-
    /apis/source.toolkit.fluxcd.io/v1beta2/namespaces/ocm-system/helmcharts/ocm-system-ocm-test-local-helm-echo-server
status:
  conditions:
    - lastTransitionTime: '2024-04-22T12:26:48Z'
      message: building artifact
      observedGeneration: 1
      reason: ProgressingWithRetry
      status: 'True'
      type: Reconciling
    - lastTransitionTime: '2024-04-22T12:26:48Z'
      message: >-
        chart pull error: failed to get chart version for remote reference:
        could not get tags for "ocm-test-echo-server": unable to locate any tags
        in provided repository:
        oci://registry.ocm-system.svc.cluster.local:5000/sha-4286669090502006150/ocm-test-echo-server
      observedGeneration: 1
      reason: ChartPullError
      status: 'False'
      type: Ready
    - lastTransitionTime: '2024-04-22T12:25:13Z'
      message: >-
        chart pull error: failed to get chart version for remote reference:
        could not get tags for "ocm-test-echo-server": unable to locate any tags
        in provided repository:
        oci://registry.ocm-system.svc.cluster.local:5000/sha-4286669090502006150/ocm-test-echo-server
      observedGeneration: 1
      reason: ChartPullError
      status: 'True'
      type: FetchFailed
  observedGeneration: -1
spec:
  chart: ocm-test-echo-server
  interval: 10s
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: ocm-test-local-helm-echo-server
  version: '*'
```

This is my used FluxDeployer manifest:
```yaml
apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: ocm-test-local-helm-echo-server
  namespace: ocm-system
spec:
  interval: 10s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Resource
    name: ocm-test-local-helm-echo-server 
    namespace: ocm-system
  helmReleaseTemplate:
    chart:
      spec:
        chart: "ocm-test-echo-server" 
        interval: 10s
    values:
      replicaCount: 1
      resources:
        limits:
          cpu: 100m # overwrite value from Helm chart
    interval: 10s
    releaseName: "ocm-helm-echo-server"
    targetNamespace: ocm-target
```

Thanks in advance!

**Comment by morri-son** [comment]
Hi @Skarlso , I remember there was a similar issue @dee0sap opened, but don't have it handy :-). Can you please take a look at Jonas' case?

**Comment by Skarlso** [comment]
`pec.sourceRef.resourceRef.version` is the version of the resource which is a version string not semver.

There is no version tracking of a single resource. In-fact, if you update a version of a resource in a component version you also update the version of the component version. You can't update just one and then push the same version of the component version. You would overwrite the component.

**Comment by dee0sap** [comment]
Hey @morri-son 
I just reviewed all my tickets in github and I don't see a match for this specific case.

**Comment by jonasbreuer** [comment]
Thanks for your input. The question is part of the use-case of always having the latest resource version deployed. 
My understanding is the following and please correct me in case of a misunderstanding from my side:
with the semVer support of the ComponentVersion spec (e.g. `semver: ">=1.0.1"`) the ocm-controller reconciles the remote OCI registry and always fetches the latest component descriptor matching the semver spec. Therefore, I don't need any manual updates in the ComponentVersion CR to get the latest component descriptor in the cluster.
From my perspective the same requirements applies for the Resource CR. In my use-case I would like to automatically use the latest version of the Resource in the latest component descriptor without having to manually increase the version spec in the Resource CR.

In my above workaround I just have set a random version which does not match the version of the resource (e.g. `version: "99.99.99" # fixed version`) and it actually worked. That would match your statement "There is no version tracking of a single resource". But then I am wondering why the version spec in the Resource CR is required at all?

**Comment by Skarlso** [comment]
>From my perspective the same requirements applies for the Resource CR.

It does not. This logic only applies to the ComponentVersion CR. Since resource versions only change when a component version changes there is no point in tracking it. You don't change the CR, that's correct. You would simply push a new version to the source repository of the OCM component.

**Comment by jonasbreuer** [comment]
> > From my perspective the same requirements applies for the Resource CR.
> 
> It does not. This logic only applies to the ComponentVersion CR. Since resource versions only change when a component version changes there is no point in tracking it. You don't change the CR, that's correct. You would simply push a new version to the source repository of the OCM component.
> 
> I _think_ we made it possible to use simply `latest` as version in the Resource CR. 🤔 You can set that and it would always apply the latest version. ( But I'll have to confirm that from the code. :) )

Yes, I can confirm that using `latest` is also possible. Overall, in my tests it looks like that the `version` of a `Resource` is not used at all. Also specifying a non-existing version works.

**Comment by Skarlso** [comment]
Wait, which version are you referring to right now? Under `resourceRef`?

**Comment by jonasbreuer** [comment]
Yes, I am referring `spec.sourceRef.resourceRef.version` in the `Resource` CR

**Comment by Skarlso** [comment]
That's weird. That shouldn't be ignored. 🤔 Are you sure you can write anything in there? What gets resolved? The latest?

**Comment by jonasbreuer** [comment]
Yes, using the latest `version` spec results in the following `status`:
```
status:
  conditions:
    - lastTransitionTime: '2024-05-21T15:05:06Z'
      message: 'Applied version: 1.0.2-20240410082017'
      observedGeneration: 1
      reason: Succeeded
      status: 'True'
      type: Ready
  lastAppliedComponentVersion: 1.0.2-20240410082017
  lastAppliedResourceVersion: latest
  observedGeneration: 1
  snapshotName: picture-transformation-service-helm-chart-jlceqg3
spec:
  interval: 10s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: ComponentVersion
    name: >-
      github.tools.sap.deploy-with-confidence-trial.picture-transformation-service
    namespace: ocm-system
    resourceRef:
      extraIdentity:
        helmChart: picture-transformation-service
      name: picture-transformation-service
      version: latest
```

Isn't the resource name anyway unique and sufficient to allocate the resource entity even without a version?

**Comment by Skarlso** [comment]
I'll look into it. It definitely shouldn't ignore version.

We are using ocm to fetch things and you should be able to set extra identities as well. The name isn't necessarily unique. There could be different manifests or configs and such.

**Comment by jonasbreuer** [comment]
Thanks @Skarlso

**Comment by Skarlso** [comment]
Okay, so we don't actually pass on the version because I remember we had some trouble with that. But I'm looking into it now.

**Comment by Skarlso** [comment]
Regarding versions. There is a discussion now going on, on Slack about this.

The version is apparently not part of the identity per say. So basically, it doesn't help during lookup. We are still debating about the peculiarities.

**Comment by Skarlso** [comment]
I added some documentations as part of https://github.com/open-component-model/ocm-controller/pull/438.

**Comment by Skarlso** [comment]
This should be closed now.
