### ISSUE TITLE
Redesign how we look up resources

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm-controller#450]
Right now, we have our own way of looking up resources by reconciling ComponentDescriptors into the cluster and searching for the right component version.

We could potentially offload this to OCM library. Let _it_ figure out what component version a given resource belongs to.

**Comment by morri-son** [comment]
@fabianburth @mandelsoft sounds reasonable :-)

**Comment by morri-son** [comment]
@Skarlso will this still be valid to work on in the v2 of the controllers? If not, let's close this.

**Comment by Skarlso** [comment]
Not really relevant anymore indeed.
