### ISSUE TITLE
Add metrics & events

### ISSUE THREAD

**Issue by phoban01** [open-component-model/ocm-controller#49]
## Description

Currently logging is the only source of information made accessible about controller activity, we should also publish Kubernetes events and metrics.

Events should be used to surface significant points of interest for operators deploying and manage resources with the controllers.

Metrics should be used to monitor performance.

**Comment by nikimanoledaki** [comment]
1. [ ] initialise event recorder
2. [ ] add event func e.g. from [kustomizationreconciler](https://github.com/fluxcd/kustomize-controller/blob/df9dd9b2cb9ca1d18be0098b42640b62b0d171be/controllers/kustomization_controller.go#L974)
3. [ ] add unit tests
4. [ ] publish event when returning happy path, requeuing, or setting condition (true/false)
