### ISSUE TITLE
Namespace contained in ocm-controller chart

### ISSUE THREAD

**Issue by nexus49** [open-component-model/ocm-controller#509]
Today the namespace is part of the ocm-controller chart. This has several disadvantages:

- With this it is not possible to deploy to an already existing namespace as helm will complain that the namespace is already existing.
- When the helm release is removed there is a risk that it may remove other unreleated resources in the namespace, as the namespace will also be terminated.
- With this it is not possible to create the helm-release in the `ocm-system` namespace so it is not possible to use `--create-namespace -n ocm-system`

It would be great if you could remove the namespace from the chart. Possibly this could be problematic with ppl upgrading from an older version.

**Comment by morri-son** [comment]
@Skarlso , can you please have a look at this? 
@nexus49 I was able to install the Helm chart using 
```
helm install ocm-controller oci://ghcr.io/open-component-model/helm/ocm-controller --set cert-manager.enabled=true --create-namespace -n ocm-system --version v0.24.0
```

without any issue.

**Comment by nexus49** [comment]
not sure what you do differently. Script to reproduce:

```
kind create cluster -n ocm2
helm install ocm-controller oci://ghcr.io/open-component-model/helm/ocm-controller --set cert-manager.enabled=true --create-namespace -n ocm-system --version v0.24.0
```

![image](https://github.com/user-attachments/assets/f97a996a-4a29-4cd0-a958-08e4984b208c)

**Comment by Skarlso** [comment]
Not sure what you are doing either... this super weird, literally copy and pasted your command:

<img width="1920" alt="Screenshot 2024-09-19 at 17 24 58" src="https://github.com/user-attachments/assets/6fdb8e1c-4473-44c3-ba9d-e4f3fe56e18b">

**Comment by Skarlso** [comment]
Are you sure you don't have a cluster with that name already?

try `kind delete clusters -A`

**Comment by Skarlso** [comment]
It's bad practice to have the namespace in the chart anyways, so I'm removing it. And it prevents #512 from working so...
