### ISSUE TITLE
ocm controller uninstall returns 404

### ISSUE THREAD

**Issue by sleungcy** [open-component-model/ocm-controller#542]
Hi,

I am having an issue trying to uninstall ocm-controller with the latest version and receives a 404 not found error:

failed to download install.yaml from https://ocm.software/ocm-controller/releases/download/v0.24.13/install.yaml, status: 404 Not Found

```
GDCC66944L:podinfo-flux-repo$ ocm version
{"Major":"0", "Minor":"16", "Patch":"2", "PreRelease":"", "Meta":"", "GitVersion":"0.16.2", "GitCommit":"57076936a9fffaa4a81488440aa66628691581aa", "GitTreeState":"", "BuildDate":"2024-10-18T13:27:52Z", "GoVersion":"go1.22.5", "Compiler":"gc", "Platform":"darwin/arm64"}
GDCC66944L:podinfo-flux-repo$ ocm controller uninstall
► uninstalling ocm-controller with version latest
► got latest version "v0.24.13"
Error: ✗ failed to construct objects to apply: ✗ failed to download install.yaml file: failed to download install.yaml from https://ocm.software/ocm-controller/releases/download/v0.24.13/install.yaml, status: 404 Not Found
```

The version I used was 0.24.13, any idea why this is happening?

**Comment by morri-son** [comment]
@Skarlso can you please check that?

**Comment by Skarlso** [comment]
Uh https://github.com/open-component-model/ocm/pull/920 missed the uninstall command. 

For now, you can overwrite this value using `--base-url=https://github.com/open-component-model/ocm-controller/releases`.

I'll fix it upstream.
