### ISSUE TITLE
Write walkthrough for podify demo

### ISSUE THREAD

**Issue by phoban01** [open-component-model/ocm-controller#58]
## Description

We will should the podinfo demo reproducible by publish the necessary assets in a Git repository with an accompanying README that details the steps required to deploy the demo.

**Comment by phoban01** [comment]
This needs to be reviewed and made public once we refactor Diffusion -> Unpacker.

**Comment by Skarlso** [comment]
Done in https://github.com/open-component-model/ocm-examples/tree/main/kubernetes/podify-walkthrough
