### ISSUE TITLE
Use HTTPS to talk to the internal docker registry

### ISSUE THREAD

**Issue by souleb** [open-component-model/ocm-controller#59]

**Comment by Skarlso** [comment]
I did this during https://github.com/open-component-model/ocm-controller/pull/156.

But that PR will not work until Flux can use insecure with helm. Maybe I could extract the https part of the work. 🤷

**Comment by Skarlso** [comment]
Now will be done by #223

**Comment by Skarlso** [comment]
- The registry is now running as HTTPS.
- The controllers have been updated to use the new registry (https://github.com/open-component-model/git-controller/pull/48, https://github.com/open-component-model/mpas-product-controller/pull/26, https://github.com/open-component-model/replication-controller/pull/42)
- Developer certificate is being used
- e2e tests are all passing
