### ISSUE TITLE
Issue while deploying ocm controller on windows.

### ISSUE THREAD

**Issue by mayankraipure12** [open-component-model/ocm-controller#73]
![image](https://user-images.githubusercontent.com/120610939/211246691-85db9fc6-47a3-46b1-90a6-a2f3b62d73b5.png)

Not able to deploy ocm-controller in windows environment in a kind cluster using 
make deploy

**Comment by Skarlso** [comment]
ah thanks for reporting.

**Comment by mayankraipure12** [comment]
make build also failed

GLOBAL+I322412@W-8TTJ633 MINGW64 /c/project/ocm/workspace/ocm-controller (main)
$ make build
mkdir -p /c/project/ocm/workspace/ocm-controller/bin
GOBIN=/c/project/ocm/workspace/ocm-controller/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.0
/c/project/ocm/workspace/ocm-controller/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./api/..." paths="./controllers/..."
-: no Go files in C:\project\ocm\workspace\ocm-controller\api
Error: not all generators ran successfully
run `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./api/... paths=./controllers/... -w` to see all available markers, or `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./api/... paths=./controllers/... -h` for usage
make: *** [generate] Error 1

**Comment by mayankraipure12** [comment]
Hi @Skarlso ,
make build doesn't work

GLOBAL+I322412@W-8TTJ633 MINGW64 /c/project/ocm/workspace/ocm-controller (main)
$ make build
mkdir -p /c/project/ocm/workspace/ocm-controller/bin
GOBIN=/c/project/ocm/workspace/ocm-controller/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.0
/c/project/ocm/workspace/ocm-controller/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./api/..." paths="./controllers/..."
-: no Go files in C:\project\ocm\workspace\ocm-controller\api
Error: not all generators ran successfully
run `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./api/... paths=./controllers/... -w` to see all available markers, or `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./api/... paths=./controllers/... -h` for usage
make: *** [generate] Error 1

**Comment by Skarlso** [comment]
Ok. but that's not what I asked. :)

Anyways, windows will not be supported at this time. Thanks.
